export const blogs_list = [
  {
    id:1,
    img_src: `https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123239/Blog.png`,
    title: "How retail shopping has changed during covid-19",
    text: "Nothing more clearly underscores how quickly the planet of retail can change than our current struggle with COVID-19.The coronavirus pandemic has made business continuity a monumental challenge for all retailers, including fashion brands who traditionally have relied on giving customers an opportunity to ascertain , feel and check out on the clothes they’re buying .Mrs. Darling first heard of Peter when she was tidying up her children’s minds. It is the nightly custom of every good mother after her children are asleep to rummage in their minds and put things straight for next morning, repacking into their proper places the many articles that have wandered during the day.If you could keep awake (but of course you can’t) you would see your own mother doing this, and you would find it very interesting to watch her. It is quite like tidying up drawers. You would see her on her knees, I expect, lingering humorously over some of your contents, wondering where on earth you had picked this thing up, making discoveries sweet and not so sweet, pressing this to her cheek as if it were as nice as a kitten, and hurriedly stowing that out of sight. When you wake in the morning, the naughtiness and evil passions with which you went to bed have been folded up small and placed at the bottom of your mind and on the top, beautifully aired, are spread out your prettier thoughts, ready for you to put on.Total store growth continued to hamper in brick & mortar, while online sales accelerated last week. Grocery and Household care rose up to be within the top-five departments. Beverages and Salty Snacks accounted for many of the Grocery growth both online and offline. For the primary time since COVID started, Alcohol lost its top-five department status.",
    Tags: ["Clothing", "Retail", "Shopping"],
    Categories: ["Outdoor_Activities", "Retail", "Shopping_Mall", "Surfing"],
    date: "July 16, 2020",
  }, {
    id:2,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123251/Blog1-1.png",
    title: "How people are shopping during covid-19",
    text: "Total store growth continued to hamper in brick & mortar, while online sales accelerated last week. Grocery and Household care rose up to be within the top-five departments. Beverages and Salty Snacks accounted for many of the Grocery growth both online and offline. For the primary time since COVID started, Alcohol lost its top-five department status.Ice skating most likely created in Scandinavia as right on time as 1000 BCE, the main skates being produced using shank or rib bones of elk, bulls, reindeer, and different creatures. It isn’t known when the metal sprinter was presented, however early Dutch prints delineate skates with metal cutting edges. Until the center of the nineteenth century the metal segment of the skate was secured to a wooden base or footplate and the entire of the skate was attached to the foot with cowhide straps or lashes. A significant improvement originated from the United States in 1850 when E.W. Bushnell of Philadelphia presented the all-steel skate, which supplanted the bulky wooden footplate. The principle advancements in the figure skate after 1900 were the option of the toe pick, a gathering of sawlike teeth situated at the toe of the sharp edge, which empowered skaters to acquire better buy in the ice while doing certain bounces, and the development of the “shut toe” cutting edge of one-piece steel, which added solidarity to the skate and allowed an a lot lighter-weight edge.As an entertainment skating has been consistently rehearsed on the waterways of the Netherlands since the Middle Ages by the two guys and females. Skating on the solidified lakes and fens was mainstream in England in the seventeenth century, and the primary skating club was framed in Edinburgh, Scotland, in 1742. During the 1740s British servicemen acquainted ice skating with North America. It was likewise mainstream at the French court around 1776; Marie-Antoinette was among the skaters. Napoleon Bonaparte skated at Auxerre in 1781  ",
    Tags: ["Covid", "Grocery", "Retail"],
    Categories: ["Outdoor_Activities", "Retail"],
    date: "July 16, 2020",
  }, {
    id:3,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123257/Blog2.png",
    title: "Keeping your stock full during a pandemic",
    text: "As the COVID-19 crisis continues, so does people’s got to safely obtain basic necessities. More and more, folks are turning to online grocery services to urge their essentials delivered as they struggle to remain socially distanced. It’s an excellent option, especially for those that are at a better risk from the virus, but if you’ve never shopped for groceries online, now could also be a very confusing and chaotic time to start out . Many stores and services are stretched thin, handling increased demand both for the products themselves and for delivery. If you’re struggling to seek out the simplest option, or if you aren’t sure where to start , we’ve compiled an inventory of resources and tips for getting groceries delivered to your home.At this specific point in the semester, it’s elusive a period where you’re really exhausted. We’re all occupied with reading for finals, getting ready for introductions, and packing to compose entire expositions in a single night. Truly soon the semester will be finished, and you’ll enter winter break for some truly necessary rest and revival. Once in a while, in the many long stretches of break between semesters, we become lost with the absence of work to be done, and end up exhausted.",
    Tags: ["Ecommerce", "Grocery", "Retail", "Stock"],
    Categories: ["Indoor_Activities", "Retail"],
    date: "July 16, 2020",
  }
  , {
    id:4,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123310/Blog3-1.png",
    title: "Staying safe while buying grocery",
    text: "Wear a mask, but skip the gloves. Don’t sanitize the apples. And if you’re older than 65, it’s probably best to still order your groceries online.As a food virologist, I hear tons of questions from people about the coronavirus risks in grocery stores and the way to remain safe while buying food amid the pandemic. Here are answers to a number of the common questions. Have you been feeling burdened by your jacket and numerous layers as of late? Does having an umbrella as a basic ordinary thing hose your soul? Obviously it does, as in summer it’s everything about flip tumbles and shorts/skirts/dresses. Goodness, how we long for the days when you can go out with only a couple of things on, appreciating the light breeze and absence of layers.Picnics, BBQ’s or any in the open air eating is quite marvelous in summer. There’s nothing more charming than sitting outside and partaking in great food together. Regardless of whether you’re abroad, eating in a sea shore eatery or having an excursion in the recreation center, food tastes 100% better in summer.Strawberries, melon, honeydew, raspberry, peaches and the rundown is interminable. Summer carry us such a significant number of delectable flavors with its organic products! Additionally they are solid (on the off chance that they are developed normally) too, not simply scrumptious.Eating frozen yogurt in winter doesn’t exactly have a similar impact isn’t that right? Frozen yogurt is cool, invigorating and in particular flavorful so it’s optimal in summer. Getting a charge out of a frozen yogurt on a late spring’s day is flawlessness and for reasons unknown, faultless when it’s hot (right?).You need to concede nothing feels better than strolling around without any shoes every minute of every day OHHHHHrgasmic! Obviously you won’t go wherever without any shoes on however flip lemon are most people groups #1 choice, I mean, having shoes is a benefit, that sadly not every person has, yet feeling the earth under you feet is an encounter we as a whole can have yet a large portion of us don’t consider this little pleasure. Dare yourself to encounter this, SO IT’S TIME TO GET A PEDICURE AND EXPOSE TO THE SUN THOSE BEAUTIFUL TOES!",
    Tags: ["Flower", "Grocery", "Shop", "Shopping"],
    Categories: ["Hotel", "Outdoor_Activities", "Retail", "Shopping_Mall"],
    date: "July 16, 2020",
  }
  , {
    id:5,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123245/Blog1.png",
    title: "Picking right grocery sites for reliable delivery",
    text: "Wear a mask, but skip the gloves. Don’t sanitize the apples. And if you’re older than 65, it’s probably best to still order your groceries online.As a food virologist, I hear tons of questions from people about the coronavirus risks in grocery stores and the way to remain safe while buying food amid the pandemic. Here are answers to a number of the common questions.There is nothing amiss with exhibiting certifiable snapshots of triteness, obviously. The initial scene alone yielded a lot of those – enough to hold your enthusiasm without uncovering basic snapshots of bluntness and playing for chuckles. Lodging monitor Alasdair’s prospering of his measuring tape with the clarification: “I squeezed this out of my mom’s sewing box. She’s been dead for more than 20 years,” needn’t bother with much else. He is likewise a wellspring of certifiable, intentional amusingness (for instance, his remark when no one comes running when he tests the crisis rope in a washroom – “I can simply lie here and drain, I wouldn’t fret”), which tosses the other dishonesty “chuckles” pointedly into alleviation.With the travel industry at a standstill, some hotels hope gift card discounts can lure future guests and drive much-needed revenue. Napa Valley’s Calistoga motor hotel & Spa, for instance , is currently housing essential personnel, but the property is looking beyond the Covid-19 crisis with a suggestion of a $50 bonus for those that purchase an e-gift card of $200 or more. The Inn at Avila Beach, a California all-inclusive that’s shuttered until early May, is offering 20% off all gift cards. Maine’s Higgins Beach Inn, which plans to open by May 29, has launched an identical offer, tacking on an additional $20 for each $100 gift card purchase.But while numerous independent and boutique hotels are banking on gift card sales to assist tide them over, their promotions could be reaching a comparatively limited audience.",
    Tags: ["Grocery", "Shop", "Shopping"],
    Categories: ["Retail", "Shopping_Mall"],
    date: "July 16, 2020",
  }
  , {
    id:6,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123235/6.jpg",
    title: "Innovation is changing the mall industries",
    text: "This means that the stores will still exist, with a stress on stores in shopping malls. However, stores in shopping centres are going to be more like customer experience centres. With e-commerce offering deep discounts, deals and incentives, transactions are going to be majorly done on online stores. Designers will got to deal with this paradigm shift and see how the functioning cost are often minimised. With this upfront the industry shouldn’t be surprised to witness more of high-street models wherein designers hamper the investments by reducing ‘Engineering Loads’. the thought of air-conditioned atriums may cease, and open courtyards would replace them soon. Despite the Retailpocalypse, designers will push hard for design flavours which can push offline sales also as online sales.Sensory experiences are going to be key. they’re going to be the most important difference between online shopping and offline shopping. With increase in digitisation, haptic experiences will gain high importance, with the shop space becoming an area to experience products using all our senses, and in fact , with the assistance of multi-sensory technology.For Millennials today, shopping is an act of fun, a recreational activity during which the transaction has become completely secondary. So, with the new generation distinguishing sharply between shopping and buying, what is going to bring back a customer to the store? it’s satisfaction, customer experience. this is often where shop-fitters. they need to help to make sure that customers who step into the shop spend longer for the experience, through a ‘different’ space arrangement, enhanced product presentation, personalised customer care and ultimately be more loyal to the retailer. the essential shopping concept shall not change such a lot . However, the presentation at the point-ofsale and therefore the involvement of the customer in it’ll . Retailers will need to offer customers more incentives to go to a store and stay there longer.",
    Tags: [],
    Categories: ["Retail"],
    date: "July 16, 2020",
  }
  , {
    id:7,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123322/Blog5-1.png",
    title: "Getting safe delivery during this pandemic",
    text: "If the delivery provider maintains all the standards then it is safe to have get products delivered to you. It is hard to maintain but still safer to get your products ordered online and get delivered to your home rather than you going to the supermarket or in any stores.I don’t speak of specific museums but rather of the conservation of historical objects and their display within the times . While these objects from the past—seen within the here and now—belong to the times , they even have no present use. There are in fact other objects—urban buildings for example—that have their origins within the past but, through their use by their inhabitants, they become integrated into the times . But objects placed during a museum aren’t used for any practical purposes: they continue to be witnesses of the past, a time external to our world. Thus, they’re meta-objects, occupying an area outside of our world, during a space that Michel Foucault defined as heterotopic space. And if one wants a definition of art, it’s the following: art consists of the objects that remain after the cultures which produced them have disappeared.From its beginning, the artwork is handled during a way that permits it to survive culture. While one often speaks about the artwork as a commodity, it’s not a traditional commodity. the traditional commodity is formed to be consumed—in other words, to be destroyed (eaten as bread, used as a car). So, during a certain sense, art is an anti-commodity. it’s anesthetize the condition of conservation—prevented from being destroyed by time and by use. And this, actually, is that the essential characteristic of art: it survives its original culture, taking an extended journey through all the opposite , later cultures. It remains at an equivalent time foreign to those other cultures—an alien in their midst, carrying with it the knowledge of its past.",
    Tags: ["Delivery", "Gro", "Online"],
    Categories: ["Delivery", "Retail"],
    date: "July 16, 2020",
  }
  , {
    id:8,
    img_src: "https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/07/07123303/Blog2-1.png",
    title: "Food delivery booming during covid-19",
    text: "Being grateful for what you have in your life as opposed to running behind what you don’t have is the best thing you can do. The need to accomplish something is unending and can go on everlastingly however on the off chance that you generally grumble about your present status and run behind accomplishing more, you will never be glad. rather, be thankful for what you have today and be fought which will satisfy you with bliss.Consider that you are so grateful to have certain extraordinary individuals throughout your life. Or on the other hand perhaps how karma you are to have a vocation in an economy like the one we’re in. Also, from that point onward, make it one stride further. Attempt and make that sentiment of appreciation much greater. Express gratefulness for the way that you have a capable body, and a functioning psyche. Express appreciation for the way that you’re solid. And afterward comes the hardest piece of all, attempting to be charitable and loaded with appreciation for whatever experience you’re given, regardless of whether it be lovely or not.So a significant number of us are worriers. Life moves rapidly, and a great deal of the time it might feel like we can scarcely keep up. The every day changes and clearing schedules leave our heads humming with contemplations and sentiments of worry on for all intents and purposes a moment by-minute premise. Some of the time it’s the everyday stuff like, “Did I make sure to bolt the entryway before I left the loft?” or “Did I neglect to kill the espresso pot before work at the beginning of today?” Other occasions, it’s more thick. Contemplations more along the lines of “Am I losing myself in the disarray of adulthood?” or “How am I going to have the option to deal with the entirety of my defects?” Sometimes, we don’t have the foggiest idea what precisely we’re stressing over. In some cases, we simply feel it swimming under our skin.",
    Tags: ["Delivery", "Ecommerce", "Food", "Restaurant"],
    Categories: ["Delivery", "Retail"],
    date: "July 16, 2020",
  }
]