export const ProductsList =[
  {
    id:"1",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125812/Footwear-3-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125810/Footwear-2-1.png",
    title:"FIRETRAP Savoy Mens Shoes",
    detail:"Footwear refers to garments worn on the feet, which originally serves to purpose of protection against adversities of the environment, usually regarding ground textures and temperature. Footwear within the manner of shoes therefore primarily serves the aim to ease the locomotion and stop injuries",
    color:["brown"],
    real_price:50.00,
    Discounted_price:35.00,
    sizes:[6,6.5,7,7.5,8,8.5,9,9.5],
    SKU:"N/A",
    Category:"Footwear",
    Tags :["Comfort","Fit","Formal"],
    CustomerReviews:"",
  },{
    id:"2",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125539/Footwear-8-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125537/Footwear-7-1.png",
    title:"KANGOL Latham Trainers Mens",
    detail:"Footwear refers to garments worn on the feet, which originally serves to purpose of protection against adversities of the environment, usually regarding ground textures and temperature. Footwear within the manner of shoes therefore primarily serves the aim to ease the locomotion and stop injuries.",
    color:["black"],
    real_price:20.00,
    Discounted_price:15.00,
    sizes:[6,6.5,7,7.5,8.5,9],
    SKU:"N/A",
    Category:"Footwear",
    Tags :[ "Fit", "Joggers", "Running", "Trainer"],
    CustomerReviews:"",
  },{
    id:"3",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125841/Footwear-9-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125840/Footwear-1-1-600x772.png",
    title:"Nike X Ghosted .3 Astro Turf Trainers",
    detail:"Footwear refers to garments worn on the feet, which originally serves to purpose of protection against adversities of the environment, usually regarding ground textures and temperature. Footwear within the manner of shoes therefore primarily serves the aim to ease the locomotion and stop injuries.",
    color:["black"],
    real_price:70.00,
    Discounted_price:55.00,
    sizes:[6,6.5,7,7.5,8.5,9,10],
    SKU:"N/A",
    Category:"Footwear",
    Tags :[ "Comfort", "Soft", "Trainers"],
    CustomerReviews:"",
  },{
    id:"4",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125648/Footwear-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125646/Footwear-4-1.png",
    title:"PUMA Retaliate Mens Trainers",
    detail:"Footwear refers to garments worn on the feet, which originally serves to purpose of protection against adversities of the environment, usually regarding ground textures and temperature. Footwear within the manner of shoes therefore primarily serves the aim to ease the locomotion and stop injuries.",
    color:["black"],
    real_price:85.00,
    Discounted_price:70.00,
    sizes:[6,6.5,7,7.5,8,8.5],
    SKU:"N/A",
    Category:"Footwear",
    Tags :[ "Running", "Soft"],
    CustomerReviews:"",
  },{
    id:"5",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124254/Blazers-20.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124302/Blazers-1-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124313/Blazers-16-1-600x772.png",
    title:"Lipsy Black Jersey Ruched Sleeve Blazer",
    detail:"A blazer may be a sort of jacket resembling a suit jacket, but cut more casually. A blazer is usually distinguished from a blazer as a more formal garment and tailored from solid colour fabrics. Blazers often have naval-style metal buttons to reflect their origins as jackets worn by boating club m",
    color:["black"],
    real_price:110.00,
    Discounted_price:90.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Blazers",
    Tags :[ "Comfort", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"6",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03111951/Blazers-11.1-1-1.jpg",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112001/Blazers-12-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112012/Blazers-14-1-600x772.png",
    title:"Nude Herringbone Heritage Jacket",
    detail:"A blazer may be a sort of jacket resembling a suit jacket, but cut more casually. A blazer is usually distinguished from a blazer as a more formal garment and tailored from solid colour fabrics. Blazers often have naval-style metal buttons to reflect their origins as jackets worn by boating club members",
    color:["darkblue"],
    real_price:150.00,
    Discounted_price:120.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Blazers",
    Tags :["Comfort", "Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"7",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112328/Blazers-2-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112332/Blazers-3-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112341/Blazers-10-1-600x772.png",
    title:"Plum Relaxed Soft Crepe Blazer",
    detail:"A blazer may be a sort of jacket resembling a suit jacket, but cut more casually. A blazer is usually distinguished from a blazer as a more formal garment and tailored from solid colour fabrics. Blazers often have naval-style metal buttons to reflect their origins as jackets worn by boating club members",
    color:["Green", "Orange", "Red", "Yellow"],
    real_price:140.00,
    Discounted_price:120.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Blazers",
    Tags :["Comfort", "Fit", "No_Zip", "Skin_Fit"],
    CustomerReviews:"",
  },{
    id:"8",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03111535/Blazers-5.1-1.jpg",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03111543/Blazers-6-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03111546/Blazers-7-1-600x772.png",
    title:"Rose Pink Padded Coat",
    detail:"A jacket may be a mid-stomach–length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear. Some jackets are fashionable, while others function protective clothing. Jackets without sleeves are vests.",
    color:["Ligh_Pink", "Pink", "Purple", "Rose_Pink"],
    real_price:90.00,
    Discounted_price:110.00,
    sizes:["S","M","XL"],
    SKU:"N/A",
    Category:"Blazers",
    Tags :["Comfort", "Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"9",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124359/Blazers-17-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124355/Blazers-4-1.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124409/Blazers-19-1-600x772.png",
    title:"Sage Linen Blend Blazer",
    detail:"A blazer may be a sort of jacket resembling a suit jacket, but cut more casually. A blazer is usually distinguished from a blazer as a more formal garment and tailored from solid colour fabrics. Blazers often have naval-style metal buttons to reflect their origins as jackets worn by boating club members",
    color:[],
    real_price:80.00,
    Discounted_price:60.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Blazers",
    Tags :["Comfort", "Fit", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"10",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113156/Casual-Wear-3-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113220/Casual-Wear-5-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113232/Casual-Wear-6-1-600x772.png",
    title:"Black Crew Neck T-Shirt",
    detail:"Casual wear (casual attire or clothing) may be a Western code that’s relaxed, occasional, spontaneous and fitted to everyday use. Casual wear became popular within the Western world following the counterculture of the 1960s. When emphasising casual wear’s comfort, it’s going to be mentioned as leisurewear.",
    color:["Black"],
    real_price:25.00,
    Discounted_price:15.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :[ "Comfort", "No_Zip", "Running"],
    CustomerReviews:"",
  },{
    id:"11",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113151/Casual-Wear-14-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113136/Casual-Wear-18.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113143/Casual-Wear-2-1-600x772.png",
    image_src4:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113204/Casual-Wear-15-1-600x772.png",
    title:"Neutral Scoop Neck Shirt",
    detail:"Casual wear (casual attire or clothing) may be a Western code that’s relaxed, occasional, spontaneous and fitted to everyday use. Casual wear became popular within the Western world following the counterculture of the 1960s. When emphasising casual wear’s comfort, it’s going to be mentioned as leisurewear.",
    color:["White"],
    real_price:50.00,
    Discounted_price:35.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :["Comfort", "Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"12",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113209/Casual-Wear-7-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113241/Casual-Wear-9-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113245/Casual-Wear-10-1-600x772.png",
    title:"White Casual Shirt",
    detail:"Casual wear (casual attire or clothing) may be a Western code that’s relaxed, occasional, spontaneous and fitted to everyday use. Casual wear became popular within the Western world following the counterculture of the 1960s. When emphasising casual wear’s comfort, it’s going to be mentioned as leisurewear.",
    color:["White"],
    real_price:35.00,
    Discounted_price:25.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :["Fit", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"13",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112835/Casual-Wear-17-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112828/Casual-Wear-16-1.png",
    title:"White Cotton Rich Shirt",
    detail:"Casual wear (casual attire or clothing) may be a Western code that’s relaxed, occasional, spontaneous and fitted to everyday use. Casual wear became popular within the Western world following the counterculture of the 1960s. When emphasising casual wear’s comfort, it’s going to be mentioned as leisurewear.",
    color:["White"],
    real_price:35.00,
    Discounted_price:25.00,
    sizes:["M","L","XL"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :["Fit", "Running", "Soft"],
    CustomerReviews:"",
  },{
    id:"14",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113002/Casual-Wear-12-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03112955/Casual-Wear-1-1.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113006/Casual-Wear-13-1-600x772.png",
    title:"White Oxford Shirt",
    detail:"Casual wear (casual attire or clothing) may be a Western code that’s relaxed, occasional, spontaneous and fitted to everyday use. Casual wear became popular within the Western world following the counterculture of the 1960s. When emphasising casual wear’s comfort, it’s going to be mentioned as leisurewear.",
    color:["White"],
    real_price:45.00,
    Discounted_price:30.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :["Comfort", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"15",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124132/Hoodies-3-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124128/Hoodies-2-1.png",
    title:"Lipsy Black Jersey Ruched Sleeve Hoodie",
    detail:"A hoody (also spelt hoodie, and alternatively referred to as a hooded sweatshirt) may be a sweatshirt with a hood. Hoodies often include a muff sewn onto the lower front, and (usually) a drawstring to regulate the hood opening.",
    color:["Black"],
    real_price:45.00,
    Discounted_price:30.00,
    sizes:["S","M","XL"],
    SKU:"N/A",
    Category:"Hoodies",
    Tags :["No_Zip", "Soft"],
    CustomerReviews:"",
  },{
    id:"16",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123948/Hoodies-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123942/Hoodies-4-1.png",
    title:"Nike Tech Fleece Full Zip Hoody",
    detail:"A hoody (also spelt hoodie, and alternatively referred to as a hooded sweatshirt) may be a sweatshirt with a hood. Hoodies often include a muff sewn onto the lower front, and (usually) a drawstring to regulate the hood opening.",
    color:["Black"],
    real_price:60.00,
    Discounted_price:45.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Hoodies",
    Tags :[ "Fit", "Soft", "Zip"],
    CustomerReviews:"",
  },{
    id:"17",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123843/Hoodies-8-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123849/Hoodies-9-1-600x772.png",
    title:"Superdry Vintage Logo Duo Hoody",
    detail:"A hoody (also spelt hoodie, and alternatively referred to as a hooded sweatshirt) may be a sweatshirt with a hood. Hoodies often include a muff sewn onto the lower front, and (usually) a drawstring to regulate the hood opening.",
    color:["Black"],
    real_price:65.00,
    Discounted_price:40.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Hoodies",
    Tags :["Skin_Fit", "Soft", "Trainers"],
    CustomerReviews:"",
  },{
    id:"18",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124741/Jackets-12-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124748/Jackets-14-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124752/Jackets-15-1-600x772.png",
    title:"Black Signature Leather Racer Jacket",
    detail:"A jacket may be a mid-stomach–length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear. Some jackets are fashionable, while others function protective clothing. Jackets without sleeves are vests.",
    color:["Black"],
    real_price:250.00,
    Discounted_price:200.00,
    sizes:["M","L","XL"],
    SKU:"N/A",
    Category:"Jackets",
    Tags :["Lether", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"19",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124656/Jackets-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124650/Jackets-4-1.png",
    title:"Camel Cord Jacket",
    detail:"A jacket may be a mid-stomach–length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear. Some jackets are fashionable, while others function protective clothing. Jackets without sleeves are vests.",
    color:["Brown"],
    real_price:165.00,
    Discounted_price:140.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Jackets",
    Tags :["Fit", "Lether"],
    CustomerReviews:"",
  },{
    id:"20",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124938/Jackets-10-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124926/Jackets-2-1.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124932/Jackets-3-1-600x772.png",
    title:"Faux Leather Jacket TRF",
    detail:"A jacket may be a mid-stomach–length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear. Some jackets are fashionable, while others function protective clothing. Jackets without sleeves are vests.",
    color:["Black"],
    real_price:170.00,
    Discounted_price:140.00,
    sizes:["S","L","XL"],
    SKU:"N/A",
    Category:"Jackets",
    Tags :["Lether", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"21",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124531/Jackets-16-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124523/Jackets-18.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124527/Jackets-1-2-600x772.png",
    title:"Lipsy Quilted Leather Jacket",
    detail:"A jacket may be a mid-stomach–length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear. Some jackets are fashionable, while others function protective clothing. Jackets without sleeves are vests.",
    color:["Black"],
    real_price:280.00,
    Discounted_price:250.00,
    sizes:["S","M","XL"],
    SKU:"N/A",
    Category:"Jackets",
    Tags :[ "Lether", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"22",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120839/Jeans-13-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120832/Jeans-12-1.png",
    title:"Dark Wash Slim Fit Jeans",
    detail:"Jeans are a kind of pants or trousers, typically made up of denim or dungaree cloth. Often the term “jeans” refers to a specific sort of trousers, called “blue jeans”, which were invented by Jacob W. Davis in partnership with Levi Strauss & Co. in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873. before the Levi Strauss patented trousers, the term “blue jeans” had been long in use for various garments (including trousers, overalls, and coats), constructed from blue-colored denim.",
    color:["darkblue"],
    real_price:60.00,
    Discounted_price:45.00,
    sizes:[30,32,34,36,38],
    SKU:"N/A",
    Category:"Jeans",
    Tags :[ "Comfort", "Fit", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"23",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123621/Jeans-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123618/Jeans-4-1.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123623/Jeans-6-1-600x772.png",
    image_src4:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123626/Jeans-7-1-600x772.png",
    title:"Grey Lift, Slim And Shape Skinny Jeans",
    detail:"Jeans are a kind of pants or trousers, typically made up of denim or dungaree cloth. Often the term “jeans” refers to a specific sort of trousers, called “blue jeans”, which were invented by Jacob W. Davis in partnership with Levi Strauss & Co. in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873. before the Levi Strauss patented trousers, the term “blue jeans” had been long in use for various garments (including trousers, overalls, and coats), constructed from blue-colored denim.",
    color:["blue"],
    real_price:60.00,
    Discounted_price:55.00,
    sizes:[30,32,34,36,38,40],
    SKU:"N/A",
    Category:"Jeans",
    Tags :["Skin_Fit", "Soft", "Zip"],
    CustomerReviews:"",
  },{
    id:"24",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120940/Jeans-11-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120938/Jeans-10-1.png",
    title:"Levi’s® 511™ Slim Fit Jeans",
    detail:"Jeans are a kind of pants or trousers, typically made up of denim or dungaree cloth. Often the term “jeans” refers to a specific sort of trousers, called “blue jeans”, which were invented by Jacob W. Davis in partnership with Levi Strauss & Co. in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873. before the Levi Strauss patented trousers, the term “blue jeans” had been long in use for various garments (including trousers, overalls, and coats), constructed from blue-colored denim.",
    color:["black"],
    real_price:130.00,
    Discounted_price:100.00,
    sizes:[34,38,42],
    SKU:"N/A",
    Category:"Jeans",
    Tags :["Fit", "Running", "Skin_Fit", "Soft", "Zip"],
    CustomerReviews:"",
  },{
    id:"25",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123728/Jeans-1-2.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03123734/Jeans-3-1-600x772.png",
    title:"Mid Wash Relaxed Skinny Jeans",
    detail:"Jeans are a kind of pants or trousers, typically made up of denim or dungaree cloth. Often the term “jeans” refers to a specific sort of trousers, called “blue jeans”, which were invented by Jacob W. Davis in partnership with Levi Strauss & Co. in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873. before the Levi Strauss patented trousers, the term “blue jeans” had been long in use for various garments (including trousers, overalls, and coats), constructed from blue-colored denim.",
    color:[],
    real_price:75.00,
    Discounted_price:60.00,
    sizes:[30,34,36,38],
    SKU:"N/A",
    Category:"Jeans",
    Tags :["Skin_Fit", "Soft", "Zip"],
    CustomerReviews:"",
  },{
    id:"26",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120422/Jeans-8-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120429/Jeans-9-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120440/Jeans-15-1-600x772.png",
    title:"Rinse Boot Cut Jeans",
    detail:"Jeans are a kind of pants or trousers, typically made up of denim or dungaree cloth. Often the term “jeans” refers to a specific sort of trousers, called “blue jeans”, which were invented by Jacob W. Davis in partnership with Levi Strauss & Co. in 1871 and patented by Jacob W. Davis and Levi Strauss on May 20, 1873. before the Levi Strauss patented trousers, the term “blue jeans” had been long in use for various garments (including trousers, overalls, and coats), constructed from blue-colored denim.",
    color:["Black"],
    real_price:55.00,
    Discounted_price:40.00,
    sizes:[30,34,36,40],
    SKU:"N/A",
    Category:"Jeans",
    Tags :["Comfort", "Skin_Fit", "Soft", "Zip"],
    CustomerReviews:"",
  },{
    id:"27",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03103152/Sports-wear-2-2.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03103158/Sports-wear-3-2-600x768.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03103140/Sports-wear-15-600x760.png",
    title:"Nike Pro Mesh Top with Leggins",
    detail:"Sportswear or activewear is clothing, including footwear, worn for sport or workout . Sport-specific clothing is worn for many sports and workout , for practical, comfort or safety reasons.Typical sport-specific garments include tracksuits, shorts, T-shirts and polo shirts. Specialized garments include swimsuits (for swimming), wet suits (for diving or surfing), ski suits (for skiing) and leotards (for gymnastics). Sports footwear include trainers, football boots, riding boots, and ice skates. Sportswear also includes bikini and a few crop tops and undergarments, like the jockstrap and sports bra. Sportswear is additionally sometimes worn as casual fashion clothing.",
    color:["red"],
    real_price:30.00,
    Discounted_price:25.00,
    sizes:["M","L","XL"],
    SKU:"N/A",
    Category:"Sports",
    Tags :["Running", "Skin_Fit", "Soft", "Trainers"],
    CustomerReviews:"",
  },{
    id:"28",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113540/Sports-Wear-6-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113546/Sports-Wear-7-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113522/Sports-Wear-2-3-600x772.png",
    title:"Nike Dri-FIT Fleece Training Joggers",
    detail:"Sportswear or activewear is clothing, including footwear, worn for sport or workout . Sport-specific clothing is worn for many sports and workout , for practical, comfort or safety reasons.Typical sport-specific garments include tracksuits, shorts, T-shirts and polo shirts. Specialized garments include swimsuits (for swimming), wet suits (for diving or surfing), ski suits (for skiing) and leotards (for gymnastics). Sports footwear include trainers, football boots, riding boots, and ice skates. Sportswear also includes bikini and a few crop tops and undergarments, like the jockstrap and sports bra. Sportswear is additionally sometimes worn as casual fashion clothing.",
    color:["black"],
    real_price:75.00,
    Discounted_price:60.00,
    sizes:["S","M","L","XL"],
    SKU:"N/A",
    Category:"Sports",
    Tags :["Fit", "No_Zip", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"29",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113737/Sports-Wear-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113735/Sports-Wear-4-1-600x772.png",
    title:"Nike Gym Vintage Joggers",
    detail:"Sportswear or activewear is clothing, including footwear, worn for sport or workout . Sport-specific clothing is worn for many sports and workout , for practical, comfort or safety reasons.",
    color:["black"],
    real_price:30.00,
    Discounted_price:25.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Sports",
    Tags :[ "Comfort", "Running"],
    CustomerReviews:"",
  },{
    id:"30",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113852/Sports-Wear-10-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113906/Sports-Wear-13-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03113902/Sports-Wear-12-1-600x772.png",
    title:"Nike Yoga Black Luxe 7/8 Leggings",
    detail:"Typical sport-specific garments include tracksuits, shorts, T-shirts and polo shirts. Specialized garments include swimsuits (for swimming), wet suits (for diving or surfing), ski suits (for skiing) and leotards (for gymnastics). Sports footwear include trainers, football boots, riding boots, and ice skates. Sportswear also includes bikini and a few crop tops and undergarments, like the jockstrap and sports bra. Sportswear is additionally sometimes worn as casual fashion clothing.",
    color:["black"],
    real_price:30.00,
    Discounted_price:25.00,
    sizes:["M","L","XL"],
    SKU:"N/A",
    Category:"Sports",
    Tags :[ "Comfort", "No_Zip", "Running", "Soft"],
    CustomerReviews:"",
  },{
    id:"31",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03114053/Sports-Wear-1-3.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03114051/Sports-Wear-16-600x772.png",
    title:"Under Armour Challenger 2 Tracksuit",
    detail:"Typical sport-specific garments include tracksuits, shorts, T-shirts and polo shirts. Specialized garments include swimsuits (for swimming), wet suits (for diving or surfing), ski suits (for skiing) and leotards (for gymnastics). Sports footwear include trainers, football boots, riding boots, and ice skates. Sportswear also includes bikini and a few crop tops and undergarments, like the jockstrap and sports bra. Sportswear is additionally sometimes worn as casual fashion clothing.",
    color:["gray"],
    real_price:50.00,
    Discounted_price:40.00,
    sizes:["S","L","XL"],
    SKU:"N/A",
    Category:"Sports",
    Tags :["Running", "Soft", "Trainers", "Zip"],
    CustomerReviews:"",
  },{
    id:"32",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120234/Kids-Wear-7-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120228/Kids-Wear-6-1-600x772.png",
    title:"Superdry Basic Polo",
    detail:"Children’s clothing/ kids wear is usually more casual than adult clothing, fit play and rest. Hosiery is usually used. More recently, however, tons of childrenswear is heavily influenced by trends in adult fashion. thanks to the increase of social media platforms like Instagram, celebrities and fashion bloggers are using their accounts to post pictures of their children wearing luxury “street style” clothing, thus inspiring parents to decorate their children as they might dress themselves. Children’s clothing is care about their health. Good quality, neat , garments are now a priority for a growing number of oldsters and children’s clothing is getting a major place in top label stores and high-end fashion shops . Dresses also are getting separately designed for boys and girls at a really early age.",
    color:["darkblue"],
    real_price:30.00,
    Discounted_price:20.00,
    sizes:["S","M"],
    SKU:"N/A",
    Category:"Kids_Wear",
    Tags :["Fit", "No_Zip", "Soft"],
    CustomerReviews:"",
  },{
    id:"33",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03115926/child-wear-1.jpg",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03115926/child-wear-1.jpg",
    title:"Lipsy Girl White Eyelash Girl Tee",
    detail:"Children’s clothing/ kids wear is usually more casual than adult clothing, fit play and rest. Hosiery is usually used. More recently, however, tons of childrenswear is heavily influenced by trends in adult fashion",
    color:["gray"],
    real_price:15.00,
    Discounted_price:12.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Kids_Wear",
    Tags :["Comfort", "Fit", "Running", "Soft"],
    CustomerReviews:"",
  },{
    id:"34",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120043/Kids-Wear-2-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03120048/Kids-Wear-3-1-600x772.png",
    title:"White Long Sleeve Smart Shirt",
    detail:"Children’s clothing/ kids wear is usually more casual than adult clothing, fit play and rest. Hosiery is usually used. More recently, however, tons of childrenswear is heavily influenced by trends in adult fashion. thanks to the increase of social media platforms like Instagram, celebrities and fashion bloggers are using their accounts to post pictures of their children wearing luxury “street style” clothing, thus inspiring parents to decorate their children as they might dress themselves. Children’s clothing is care about their health. Good quality, neat , garments are now a priority for a growing number of oldsters and children’s clothing is getting a major place in top label stores and high-end fashion shops . Dresses also are getting separately designed for boys and girls at a really early age.",
    color:["white"],
    real_price:30.00,
    Discounted_price:20.00,
    sizes:["S","L"],
    SKU:"N/A",
    Category:"Kids_Wear",
    Tags :["Formal", "No_Zip", "Soft"],
    CustomerReviews:"",
  },{
    id:"35",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125110/Watches-8-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125108/Watches-7-1-600x772.png",
    title:"Rolex GMT-Master II",
    detail:"A watch may be a portable timepiece intended to be carried or worn by an individual . it’s designed to stay a uniform movement despite the motions caused by the person’s activities.",
    color:[ "Diamond", "Silver"],
    real_price:12500.00,
    Discounted_price:10500.00,
    sizes:[],
    SKU:"N/A",
    Category:"Watches",
    Tags :["30mm", "Stainless"],
    CustomerReviews:"",
  },{
    id:"36",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125151/Watches-5-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125153/Watches-6-1-600x772.png",
    title:"The Horse The Resin",
    detail:"A watch may be a portable timepiece intended to be carried or worn by an individual . it’s designed to stay a uniform movement despite the motions caused by the person’s activities. A wristwatch is meant to be worn round the wrist, attached by a watch strap or other sort of bracelet, including metal bands, leather straps or the other quite bracelet. A watch is meant for an individual to hold during a pocket, often attached to a sequence . The study of timekeeping is understood as horology.",
    color:["Golden"],
    real_price:250.00,
    Discounted_price:220.00,
    sizes:[],
    SKU:"N/A",
    Category:"Watches",
    Tags :["30mm", "Lether", "Skin_Fit", "Soft"],
    CustomerReviews:"",
  },{
    id:"37",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125250/Watches-4-1-600x772.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125248/Watches-3-1.png",
    title:"The Horse Classic",
    detail:"A watch may be a portable timepiece intended to be carried or worn by an individual . it’s designed to stay a uniform movement despite the motions caused by the person’s activities. A wristwatch is meant to be worn round the wrist, attached by a watch strap or other sort of bracelet,",
    color:["Black"],
    real_price:250.00,
    Discounted_price:200.00,
    sizes:[],
    SKU:"N/A",
    Category:"Watches",
    Tags :[ "Lether", "Skin_Fit"],
    CustomerReviews:"",
  },{
    id:"38",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125320/Watches-2-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125322/Watches-9-1-600x772.png",
    title:"Emporio Armani AR2453 Men’s Chronograph",
    detail:"A watch may be a portable timepiece intended to be carried or worn by an individual . it’s designed to stay a uniform movement despite the motions caused by the person’s activities.",
    color:["black"],
    real_price:230.00,
    Discounted_price:210.00,
    sizes:[],
    SKU:"N/A",
    Category:"Watches",
    Tags :["30mm", "Stainless"],
    CustomerReviews:"",
  },{
    id:"39",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125409/Watches-1-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03125409/Watches-1-1.png",
    title:"Rolex The Oyster -Olive Green",
    detail:"A watch may be a portable timepiece intended to be carried or worn by an individual . it’s designed to stay a uniform movement despite the motions caused by the person’s activities.",
    color:["Silever","Diamond"],
    real_price:2000.00,
    Discounted_price:1800.00,
    sizes:[],
    SKU:"N/A",
    Category:"Watches",
    Tags :["Dial", "Skin_Fit"],
    CustomerReviews:"",
  },{
    id:"40",
    image_src1:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124830/Jackets-6-1.png",
    image_src2:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124842/Jackets-8-1-600x772.png",
    image_src3:"https://d1rn6kzjmi8824.cloudfront.net/wp-content/uploads/sites/9/2020/09/03124850/Jackets-9-1-600x772.png",
    title:"Khaki Cropped Utility Jacket",
    detail:"A jacket may be a mid-stomach_length garment for the upper body. A jacket typically has sleeves, and fastens within the front or slightly on the side. A jacket is usually lighter, tighter-fitting, and fewer insulating than a coat, which is outerwear.",
    color:["khaki"],
    real_price:90.00,
    Discounted_price:80.00,
    sizes:["S","M","L"],
    SKU:"N/A",
    Category:"Casual_Wear",
    Tags :["Comfort", "Khaki", "Soft"],
    CustomerReviews:"",
  }
];

